### ISSUE TITLE
请问一下VIP用户用这种方法下载会限速吗？

### ISSUE THREAD

**Issue by 0x7FFFFFFFFFFFFFFF** [MotooriKashin/BaiduYun-Escape#1]
我是付费用户，但是没有安装百度网盘的软件，不知道会不会限速？谢谢。

**Comment by MotooriKashin** [comment]
不清楚，个人没有会员，所以下小文件还行，下大文件还是用那些专业的脚本。  
接口来自底下BaiduYunHack，你可以安装那个试试。我这个强制绑定IDM+ef2，就没打算公开发布。

**Comment by 0x7FFFFFFFFFFFFFFF** [comment]
哦好的，谢谢，我看一下。
