### ISSUE TITLE
[功能请求] 允许下载文件部分

### ISSUE THREAD

**Issue by MyBlueHorizon** [MotooriKashin/BaiduYun-Escape#2]
对于媒体文件等特殊文件，可不可以添加一个下载文件部分的功能，如从文件百分之多少下载到百分之多少。

**Comment by MotooriKashin** [comment]
脚本本身并没有提供直接下载功能，只是提供下载链接给其他下载工具。浏览器本身肯定不支持，IDM应该也不行，aria2或许可以……

比起这个我更好奇你想要这个功能的意图，对于视频文件而言，应该是想要从多少秒到多少秒的不分，而不是文件本身从多少字节到多少字节。早知道：视(音)频都是经过编码的，从时间轴到字节序列很难对应，而且还有元数据（一般在文件开头)，缺少元数据没有软件能认出你下载的文件是什么格式。总之，按字节百分比截取下载毫无意义，而要视频切片的话也不能指望下载工具去干剪辑工具的。

flv或许可以，那个已经帮你切好片了——可是自从DASH上位后，flv好像也不切片了🤣

**Comment by MyBlueHorizon** [comment]
可能是之前记错了吧，之前依稀记得用VLC看过下载到一半的文件预览，没有什么大问题可能是文件头已经下载出来了吧。这次主要是看到一个把多集拼接在一块的一个视频文件，想着能不能大约单独下载特定的几个部分。
然后又想起百度云客户端经常下载半路失败（也不知道原因为啥），尤其是一些大文件...经过校验后前面的部分完好，想着能不能直接从特定字节拼接。
结合以上两个原因提出的Issue。

**Comment by MotooriKashin** [comment]
既然已经拼成一个文件，那除了下下来自己剪辑，实在没什么办法，除非某个不务正业的下载工具还集成了视频编解码功能，能够按需下载并重新编码封装指定的片段——世面上应该没有这样的软件。
